server:
  port: 8083
spring:
  cloud:
    azure:
      servicebus:
        enabled: true
        connection-string: Endpoint=sb://saranganrajan-servicebus.servicebus.windows.net;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=wtnbhcUL8ct2s9M4XvL4Pe3SkCnpvnA1Z+ASbIRv8RA=
    stream:
      bindings:
        policy-message-output:
          destination: core/policy
        customer-message-output:
          destination: core/customer
      function:
        definition: supply;
      poller:
        fixed-delay: 1000
        initial-delay: 0
      servicebus:
        bindings:
          policy-message-output:
            producer:
              entity-type: queue
          customer-message-output:
            producer:
              entity-type: queue