server:
  port: 8083
spring:
  cloud:
    azure:
      servicebus:
        enabled: true
        connection-string: Endpoint=sb://saranganrajan-servicebus.servicebus.windows.net;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=wtnbhcUL8ct2s9M4XvL4Pe3SkCnpvnA1Z+ASbIRv8RA=
    stream:
      bindings:
        policy-message-output:
          destination: core/policy
        customer-message-output:
          destination: core/customer
        policy-message-input:
          destination: core/policy
        customer-message-input:
          destination: core/customer
      function:
        definition: supply;
      poller:
        fixed-delay: 1000
        initial-delay: 0
      servicebus:
        bindings:
          policy-message-output:
            producer:
              entity-type: queue
          customer-message-output:
            producer:
              entity-type: queue
          policy-message-input:
            consumer:
              auto-complete: true
          customer-message-input:
            consumer:
              auto-complete: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 50000
      wait-timeout: 50000
    password: SingaiSaga84
    url: jdbc:mysql://148.72.232.181:3306/tamilmuthiraidb
    username: sarangapani
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: false
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000